version: '3.3'

services:
  server:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 server.asgi:application
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - main_server_volume:/home/app
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/home/app/postgresql/data/
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE
  redis:
      image: "redis:alpine"
      expose:
        - 6379
      volumes:
        - redis_data:/home/app/redis/data/
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - server
    volumes:
      - main_server_volume:/home/app

volumes:
  postgres_data:
  redis_data:
  main_server_volume:
