version: '3.3'

services:
  server:
    build: ./server
    command: daphne -b 0.0.0.0 -p 8000 server.asgi:application
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_volume:/home/app/server/staticfiles
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$SQL_USER}
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - server
    volumes:
      - static_volume:/home/app/server/staticfiles

volumes:
  postgres_data:
  static_volume:
